-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.address
(
    id bigint NOT NULL DEFAULT nextval('address_id_seq'::regclass),
    cep character varying(255) COLLATE pg_catalog."default" NOT NULL,
    complement character varying(255) COLLATE pg_catalog."default" NOT NULL,
    neighborhood character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "number" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    public_area character varying(255) COLLATE pg_catalog."default" NOT NULL,
    city_id bigint,
    address_id bigint,
    CONSTRAINT address_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.category
(
    id bigint NOT NULL DEFAULT nextval('category_id_seq'::regclass),
    name character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT category_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.city
(
    id bigint NOT NULL DEFAULT nextval('city_id_seq'::regclass),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    client_id bigint,
    state_id bigint,
    CONSTRAINT city_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.client
(
    id bigint NOT NULL DEFAULT nextval('client_id_seq'::regclass),
    client_type smallint,
    cpf_or_cpnj character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT client_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.client_order
(
    id bigint NOT NULL DEFAULT nextval('client_order_id_seq'::regclass),
    date date,
    address_id bigint,
    client_id bigint,
    CONSTRAINT client_order_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.order_product
(
    client_order_id bigint NOT NULL,
    product_id bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS public.payment
(
    client_order_id bigint NOT NULL,
    status smallint,
    CONSTRAINT payment_pkey PRIMARY KEY (client_order_id)
);

CREATE TABLE IF NOT EXISTS public.payment_card
(
    installment_number integer,
    client_order_id bigint NOT NULL,
    CONSTRAINT payment_card_pkey PRIMARY KEY (client_order_id)
);

CREATE TABLE IF NOT EXISTS public.payment_slip
(
    due_date date,
    payment_date date,
    client_order_id bigint NOT NULL,
    CONSTRAINT payment_slip_pkey PRIMARY KEY (client_order_id)
);

CREATE TABLE IF NOT EXISTS public.phone
(
    client_id bigint NOT NULL,
    phones character varying(255) COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public.product
(
    id bigint NOT NULL DEFAULT nextval('product_id_seq'::regclass),
    name character varying(20) COLLATE pg_catalog."default" NOT NULL,
    price numeric(38, 2),
    CONSTRAINT product_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.product_category
(
    product_id bigint NOT NULL,
    category_id bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS public.state
(
    id bigint NOT NULL DEFAULT nextval('state_id_seq'::regclass),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT state_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.address
    ADD CONSTRAINT fkffe4aybw86djvowd2i71xgldy FOREIGN KEY (address_id)
    REFERENCES public.client (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.address
    ADD CONSTRAINT fkpo044ng5x4gynb291cv24vtea FOREIGN KEY (city_id)
    REFERENCES public.city (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.city
    ADD CONSTRAINT fk6p2u50v8fg2y0js6djc6xanit FOREIGN KEY (state_id)
    REFERENCES public.state (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.city
    ADD CONSTRAINT fkss1yegicj4mn3d5qn6uobeg6v FOREIGN KEY (client_id)
    REFERENCES public.address (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.client_order
    ADD CONSTRAINT fkcggjtc9f3otuprl7takbttwuk FOREIGN KEY (client_id)
    REFERENCES public.client (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.client_order
    ADD CONSTRAINT fkignb84beb69yve5wu5g4pcvlr FOREIGN KEY (address_id)
    REFERENCES public.address (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.order_product
    ADD CONSTRAINT fkhnfgqyjx3i80qoymrssls3kno FOREIGN KEY (product_id)
    REFERENCES public.product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.order_product
    ADD CONSTRAINT fkq8jjmxm0o1amhmerdmw9naojn FOREIGN KEY (client_order_id)
    REFERENCES public.client_order (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.payment
    ADD CONSTRAINT fkavenyq25l4flsd48f11os4mff FOREIGN KEY (client_order_id)
    REFERENCES public.client_order (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS payment_pkey
    ON public.payment(client_order_id);


ALTER TABLE IF EXISTS public.payment_card
    ADD CONSTRAINT fk8edfcpxaie8rj6iqmms5ckbdx FOREIGN KEY (client_order_id)
    REFERENCES public.payment (client_order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS payment_card_pkey
    ON public.payment_card(client_order_id);


ALTER TABLE IF EXISTS public.payment_slip
    ADD CONSTRAINT fk1u8b612txlj38fps15hjqpn5u FOREIGN KEY (client_order_id)
    REFERENCES public.payment (client_order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS payment_slip_pkey
    ON public.payment_slip(client_order_id);


ALTER TABLE IF EXISTS public.phone
    ADD CONSTRAINT fk3o48ec26lujl3kf01hwqplhn2 FOREIGN KEY (client_id)
    REFERENCES public.client (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.product_category
    ADD CONSTRAINT fk2k3smhbruedlcrvu6clued06x FOREIGN KEY (product_id)
    REFERENCES public.product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.product_category
    ADD CONSTRAINT fkkud35ls1d40wpjb5htpp14q4e FOREIGN KEY (category_id)
    REFERENCES public.category (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;